#####################################################################################
# Date            Version            Change
# 01/03/2019      1.0                created (previous)
# 11/04/2019      2.0                backlog fixes and new features (current)
#####################################################################################
---

- hosts: "{{ hosts }}"
  become: "{{ lookup('ini', 'ANSIBLE_BECOME section=ANSIBLE file={{ configFile }}') }}"
  vars:
    file_path: "{{ lookup('ini', 'ASSETS_DIR section=LDA file={{ configFile }}') }}"
    config_template: "{{ lookup('ini', 'CONFIG_TEMPLATE section=LDA file={{ configFile }}') }}"
  tasks: 
  - name: Run setup-ds-admin.pl script
    shell: sudo /usr/sbin/setup-ds-admin.pl -s -f '{{ file_path }}/{{ config_template }}'
