---

- hosts: "{{ hosts }}"
  become: "true"
  vars:
    file_path: "{{ lookup('ini', 'ASSETS_DIR section=LDA file={{ configFile }}') }}"
    config_template: "{{ lookup('ini', 'CONFIG_TEMPLATE section=LDA file={{ configFile }}') }}"
  tasks: 
  - name: Run setup-ds-admin.pl script
    shell: /usr/sbin/setup-ds-admin.pl -s -f '{{ file_path }}/{{ config_template }}'
