---

- hosts: "{{ hosts }}"
  become: true
  vars:
    hostname: "{{ lookup('inventory_hostnames', 'LDA') }}"
  tasks:
  - include_vars:
      file: "/etc/ansible/group_vars_{{ deployment_environment }}/ldap.yml"
      name: ldap
    no_log: true

  - name: Fully Qualified Domain Name Resolution
    lineinfile:
      path: /etc/hosts
      line: "{{ inventory_hostname }} {{ hostname }}.{{ ldap.domain }} {{ hostname }}"
