---

- hosts: "{{ hosts }}"
  become: "{{ lookup('ini', 'ANSIBLE_BECOME section=ANSIBLE file={{ configFile }}') }}"
  tasks: 
  - name: " {{ state }} the 389-Directory Services"
    shell: "sudo systemctl {{ state }} dirsrv-admin"
