---


- hosts: "{{ hosts }}"
  vars: 
    repo_name: "{{ lookup('ini', 'REPO_NAME section=RPM file={{ configFile }}') }}"
  tasks:
  - name: remove 389 Directory Server instances on CentOS
    shell: /usr/sbin/remove-ds-admin.pl -y -f
 
#  - name: Remove 389 Directory Server packages
#    shell: yum remove 389-ds-base-libs 389-adminutil idm-console-framework -y

#  - name: Remove repository (and clean up left-over metadata)
#    yum_repository:
#      name: "{{ repo_name }}"
#      file: external_repos
#      state: absent
   
#  - name: clean state
#    shell: rm -rf /etc/dirsrv /usr/lib*/dirsrv /var/*/dirsrv /etc/sysconfig/dirsrv*
    
